# Chicago Risk Classification

In [1]:
import pandas as pd
from sodapy import Socrata

In [2]:
from sys import path

path.insert(0, '../modules')

import utils as f
import params_cfg as pc
import visuals

%load_ext autoreload
%autoreload 2

In [3]:
brz_path = pc.BRZ_PATH

## Police Stations

In [5]:
client = Socrata('data.cityofchicago.org', None)

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

In [ ]:
results_stations = client.get(
    'z8bn-74gv',
    select="district, district_name, latitude, longitude"
)
print('Download complete!')

df_stations = pd.DataFrame.from_records(results_stations)
df_stations = f.rm_columns(df_stations)

print('POLICE STATIONS complete!')

df_stations.head()

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

In [ ]:
df_stations.to_csv(f'{brz_path}/df_stations.csv', index=False)

## Community Area

In [8]:
results_comm = client.get(
    'igwz-8jzy',
    select='the_geom, area_numbe, community, shape_area, shape_len'
)
print('Download complete!')

df_comm = pd.DataFrame.from_records(results_comm)
df_comm = f.rm_columns(df_comm)

print('COMMUNITY AREAS complete!')

df_comm.head()

Download complete!
COMMUNITY AREAS complete!

,the_geom,area_numbe,community,shape_area,shape_len
0,"{'type': 'MultiPolygon', 'coordinates': [[[[-8...",1,ROGERS PARK,51259902.4506,34052.3975757
1,"{'type': 'MultiPolygon', 'coordinates': [[[[-8...",2,WEST RIDGE,98429094.8621,43020.6894583
2,"{'type': 'MultiPolygon', 'coordinates': [[[[-8...",3,UPTOWN,65095642.7289,46972.7945549
3,"{'type': 'MultiPolygon', 'coordinates': [[[[-8...",4,LINCOLN SQUARE,71352328.2399,36624.6030848
4,"{'type': 'MultiPolygon', 'coordinates': [[[[-8...",5,NORTH CENTER,57054167.85,31391.6697542

In [ ]:
df_comm.to_csv(f'{brz_path}/df_comm.csv', index=False)

## Census

In [9]:
results_census = client.get(
    'kn9c-c2s2',
    select="""
        ca, percent_of_housing_crowded,
        percent_households_below_poverty,
        percent_aged_16_unemployed,
        percent_aged_25_without_high_school_diploma,
        percent_aged_under_18_or_over_64,
        per_capita_income_,
        hardship_index
    """
)
print('Download complete!')

df_census = pd.DataFrame.from_records(results_census)
df_census = f.rm_columns(df_census)

print('CENSUS complete!')

df_census.head()

Download complete!
CENSUS complete!

,ca,percent_of_housing_crowded,percent_households_below_poverty,percent_aged_16_unemployed,percent_aged_25_without_high_school_diploma,percent_aged_under_18_or_over_64,per_capita_income_,hardship_index
0,1,7.7,23.6,8.7,18.2,27.5,23939,39
1,2,7.8,17.2,8.8,20.8,38.5,23040,46
2,3,3.8,24,8.9,11.8,22.2,35787,20
3,4,3.4,10.9,8.2,13.4,25.5,37524,17
4,5,0.3,7.5,5.2,4.5,26.2,57123,6

In [ ]:
df_census.to_csv(f'{brz_path}/df_census.csv', index=False)

## Districts

In [10]:
results_districts = client.get(
    '24zt-jpfn',
    select='the_geom, dist_num'
)
print(f'Download complete!')

df_districts = pd.DataFrame.from_records(results_districts)
df_districts = f.rm_columns(df_districts)

print('DISTRICTS complete!')

df_districts.head()

Download complete!
DISTRICTS complete!

                                            the_geom dist_num
0  {'type': 'MultiPolygon', 'coordinates': [[[[-8...       17
1  {'type': 'MultiPolygon', 'coordinates': [[[[-8...       20
2  {'type': 'MultiPolygon', 'coordinates': [[[[-8...       31
3  {'type': 'MultiPolygon', 'coordinates': [[[[-8...       31
4  {'type': 'MultiPolygon', 'coordinates': [[[[-8...       19

In [ ]:
df_districts.to_csv(f'{brz_path}/df_districts.csv', index=False)

## Crimes

In [6]:
results_crime = client.get(
    'ijzp-q8t2',
    select="""
            id, date, primary_type,
            arrest, domestic,
            district, community_area,
            latitude, longitude
        """,
    where="date >= '2022-01-01' and date < '2026-06-01'",
    limit=2_000_000
)
print('Download complete!')

df_crime = pd.DataFrame.from_records(results_crime)
df_crime = f.rm_columns(df_crime)

print('CRIMES complete!')

df_crime.head()

Download complete!
CRIMES complete!

,id,date,primary_type,arrest,domestic,district,community_area,latitude,longitude
0,14215443,2026-05-31T23:46:00.000,BATTERY,True,True,025,18,41.936782316,-87.796881179
1,14218539,2026-05-31T23:40:00.000,CRIMINAL DAMAGE,False,False,009,63,41.794667526,-87.693823635
2,14215420,2026-05-31T23:40:00.000,BATTERY,False,False,018,7,41.925398449,-87.652311296
3,14215495,2026-05-31T23:38:00.000,BURGLARY,False,False,009,63,41.793680219,-87.694431196
4,14215556,2026-05-31T23:35:00.000,BATTERY,False,False,011,26,41.880673557,-87.729959795

In [8]:
df_crime.to_csv(f'{brz_path}/df_crime.csv', index=False)